[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python migrate.py init || true"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:${PORT:-8000}"
